
# This file is automatically generated, you probably don't want to edit this

sdtOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "sdtOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            trial = NULL,
            sig = NULL,
            res = NULL,
            sub = NULL,
            group = NULL, ...) {

            super$initialize(
                package='resWagner',
                name='sdt',
                requiresData=TRUE,
                ...)

            private$..trial <- jmvcore::OptionVariable$new(
                "trial",
                trial)
            private$..sig <- jmvcore::OptionLevel$new(
                "sig",
                sig,
                variable="(trial)")
            private$..res <- jmvcore::OptionVariable$new(
                "res",
                res)
            private$..sub <- jmvcore::OptionVariable$new(
                "sub",
                sub,
                default=NULL)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                default=NULL)

            self$.addOption(private$..trial)
            self$.addOption(private$..sig)
            self$.addOption(private$..res)
            self$.addOption(private$..sub)
            self$.addOption(private$..group)
        }),
    active = list(
        trial = function() private$..trial$value,
        sig = function() private$..sig$value,
        res = function() private$..res$value,
        sub = function() private$..sub$value,
        group = function() private$..group$value),
    private = list(
        ..trial = NA,
        ..sig = NA,
        ..res = NA,
        ..sub = NA,
        ..group = NA)
)

sdtResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Signal Detection Theory")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Signal Detection Theory"))}))

sdtBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "sdtBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'resWagner',
                name = 'sdt',
                version = c(1,0,0),
                options = options,
                results = sdtResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Signal Detection Theory
#'
#' 
#' @param data .
#' @param trial .
#' @param sig .
#' @param res .
#' @param sub .
#' @param group .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
sdt <- function(
    data,
    trial,
    sig,
    res,
    sub = NULL,
    group = NULL) {

    if ( ! requireNamespace('jmvcore'))
        stop('sdt requires jmvcore to be installed (restart may be required)')

    options <- sdtOptions$new(
        trial = trial,
        sig = sig,
        res = res,
        sub = sub,
        group = group)

    results <- sdtResults$new(
        options = options)

    analysis <- sdtClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
